reset defences for sandbox and reword modal warning
ScottLogic/prompt-injection pull request #739
Opened 2024-01-04 14:09 UTC by heatherlogan-scottlogic

## Description

Describe what your code changes do.

## Screenshots

Where applicable, show screenshots of the visual changes.

## Notes

- Bullet point list with
- any notable code changes
- or explanations regarding this PR

## Concerns

- Bullet point list
- with any questions
- or concerns about this PR

## Checklist

Have you done the following?

- [ ] Linked the relevant Issue
- [ ] Added tests
- [ ] Ensured the workflow steps are passing

2024-01-05 11:12 UTC, gsproston-scottlogic approved these changes
Very elegant!

2024-01-08 15:31 UTC, pmarsh-scottlogic requested changes
Tidy!

Just one small change from me, which isn't even to do with the ticket

2024-01-08 15:31 UTC, pmarsh-scottlogic commented on backend/test/unit/controller/resetController.test.ts
I know not part of the ticket but can we change
```typescript
describe('handleResetAllDefences unit tests', () => {
...
```
to
```typescript
describe('handleResetProgress unit tests', () => {
...
```

2024-01-10 09:49 UTC, pmarsh-scottlogic approved these changes
Sweet-o

2024-01-10 09:52 UTC, merged