DRAFT 715 defence successfully configured message should not disappear after a delay
ScottLogic/prompt-injection pull request #778
Opened 2024-01-16 14:05 UTC by dhinrichs-scottlogic

## Description

Describe what your code changes do.

## Screenshots

Where applicable, show screenshots of the visual changes.

## Notes

- Bullet point list with
- any notable code changes
- or explanations regarding this PR

## Concerns

- Bullet point list
- with any questions
- or concerns about this PR

## Checklist

Have you done the following?

- [ ] Linked the relevant Issue
- [ ] Added tests
- [ ] Ensured the workflow steps are passing

2024-01-19 17:05 UTC, pmarsh-scottlogic commented
this change interacts amusingly with this bug #742 
Not something to block this PR, but we should prioritise the bug once this is in

2024-01-19 17:39 UTC, pmarsh-scottlogic requested changes
I've not looked at the code yet, but this is a great change!

First thing I notice is that on refresh, or changing level then back again, these lovely new messages vanish! That's because when we add an info message to the messages state object, we must also update the chatHistory in the backend. See `addInfoMessage` defined in _MainComponent.tsx_.
Almost the same problem as #741 

I'll do a proper review next week

Edit: Turns out `addInfoMessage` in MainComponenet.tsx will add the message to the front and as well as the backend history. So the fix is to use `addInfoMessage` rather than `addChatMessage`.

2024-01-22 10:23 UTC, pmarsh-scottlogic requested changes
Super sleek!

Only some minor things from me

2024-01-22 10:23 UTC, pmarsh-scottlogic commented on frontend/src/components/MainComponent/MainComponent.tsx
> +		// add info message to chat
I'd prefer no comment here. I think the code reads well already without it!

2024-01-22 10:23 UTC, pmarsh-scottlogic commented on frontend/src/components/MainComponent/MainComponent.tsx
> +			// add info message to chat
same here, don't think the comment is needed

2024-01-22 10:30 UTC, pmarsh-scottlogic commented on frontend/src/components/ModelBox/ModelConfigurationSlider.tsx
> +		addChatMessage({
You should import and use `addInfoMessage` instead. That'll sort out the refresh problem

2024-01-22 10:31 UTC, pmarsh-scottlogic commented on frontend/src/components/ModelBox/ModelSelection.tsx
> +			});
You should import and use `addInfoMessage` instead. That'll sort out the refresh problem

2024-01-23 13:19 UTC, chriswilty requested changes
One primary concern, but all else good.

I assume there are no tests covering these components? If you want to learn some Testing Library style component tests, you might consider adding some for one of the simpler components, or some around the proposed validation changes. Doesn't need to be in this PR though.

2024-01-23 13:19 UTC, chriswilty commented on frontend/src/components/MainComponent/MainComponent.tsx
> +		addInfoMessage(`${displayedDefenceId} defence reset`);
You have these two lines duplicated now; may as well pull out into a separate function, which takes param 'reset' or 'configured' for the message to add.

2024-01-30 16:06 UTC, dhinrichs-scottlogic commented
This all turned out much more complicated than anticipated, so after some discussion decided to approach it slightly differently and started again from scratch. 
New PR: https://github.com/ScottLogic/prompt-injection/pull/802

2024-01-30 16:06 UTC, closed without merging