Initial k6 setup
ScottLogic/prompt-injection pull request #813
Opened 2024-02-05 10:41 UTC by kclark-scottlogic

## Description

Initial setup PR for k6 to have first set of scenarios running properly.

Ticket #812 

## Screenshots

Where applicable, show screenshots of the visual changes.

## Notes

- Bullet point list with
- any notable code changes
- or explanations regarding this PR

## Concerns

- Bullet point list
- with any questions
- or concerns about this PR

## Checklist

Have you done the following?

- [ ] Linked the relevant Issue
- [ ] Added tests
- [ ] Ensured the workflow steps are passing

2024-02-07 08:45 UTC, pmarsh-scottlogic approved these changes
nice nice nice

2024-02-08 13:12 UTC, chriswilty reviewed
Tried it out locally, works a treat 👌 

Just a handful of suggestions

2024-02-08 13:12 UTC, chriswilty commented on k6/README.md
> +This readme is for how to install and us k6 for manual load testing
typo: "use k6"

I think a good intro paragraph would explain what we are using k6 for, and why! So yes, generally performance testing, but also worth mentioning k6 is free and open-source 💚

2024-02-08 13:12 UTC, chriswilty commented on k6/README.md
> +The link for installation of k6 can be found [here](https://grafana.com/docs/k6/latest/get-started/installation/). Follow the instructions on the link for your installer of choice
Generally speaking, linking the word "here" is not good practice. The internet is full of it though 😢

Better to have the link text describe what it is linking to:

```
[Download and install k6](https://grafana.com/docs/k6/latest/get-started/installation/)
```

2024-02-08 13:12 UTC, chriswilty commented on k6/README.md
> +1. Make sure local backend is running
Could link to the backend README here.

```
1. Start the server - [refer to the backend README](../backend/README.md)
```

2024-02-08 13:12 UTC, chriswilty commented on k6/README.md
> +1. in a sepearate terminal run ```k6 run script.js``` (Where 'script' is the name of the script you want to run)
Typo: `In a separate terminal`

Also, use single backticks for inline code, not triples.

2024-02-08 13:12 UTC, chriswilty commented on k6/smoke.js
> +  let data = { message: "hi", currentLevel: '3' };
Use a `const`.

2024-02-08 13:12 UTC, chriswilty commented on k6/smoke.js
> +    'response code was 200': (response) => response.status == 200,
Need triple-equals here.

2024-02-08 13:13 UTC, chriswilty requested changes
Whoops, forgot to submit my review as a change request

2024-02-09 10:43 UTC, chriswilty commented on k6/README.md
> +Grafana k6 is an open-source load testing tool that makes performance testing easy and productive for engineering teams. k6 is free, developer-centric, and extensible. In this project we are using k6
❤️

2024-02-09 10:45 UTC, chriswilty requested changes
Teeny tiny corrections in readme, but looking nice 👌

2024-02-09 10:45 UTC, chriswilty commented on k6/README.md
> +The link for installation of k6 can be found [Download and install k6](https://grafana.com/docs/k6/latest/get-started/installation/). Follow the instructions on the link for your installer of choice
Remove the leading "The link for installation of k6 can be found" text, as it makes no sense with that still there.

2024-02-09 10:45 UTC, chriswilty commented on k6/README.md
> +1. Make sure local backend is running [refer to the backend README](../backend/README.md)
comma after "running"

2024-02-09 11:15 UTC, chriswilty approved these changes
Sweet 👍

2024-02-09 11:16 UTC, merged