Misc tidying
ScottLogic/prompt-injection pull request #837
Opened 2024-02-15 14:05 UTC by pmarsh-scottlogic

## Description

Describe what your code changes do.

## Screenshots

Where applicable, show screenshots of the visual changes.

## Notes

- Bullet point list with
- any notable code changes
- or explanations regarding this PR

## Concerns

- Bullet point list
- with any questions
- or concerns about this PR

## Checklist

Have you done the following?

- [ ] Linked the relevant Issue
- [ ] Added tests
- [ ] Ensured the workflow steps are passing

2024-02-15 14:10 UTC, pmarsh-scottlogic commented on backend/src/controller/chatController.ts
> +	const totalSentEmails: EmailInfo[] = [
before, this was being instantiated then mutated once to add on the new emails sent as a result of the message. Now we just instantiate it including the new emails

2024-02-15 14:14 UTC, pmarsh-scottlogic commented on backend/src/langchain.ts
> -			questionAnswered: true,
We weren't using this `questionAnswered` value anywhere.

2024-02-15 14:15 UTC, pmarsh-scottlogic commented on backend/src/openai.ts
> -		return { reply: "Reply with 'I don't know what to ask'" };
there was no reason to wrap this in an object either

2024-02-15 14:28 UTC, AAloshine-scottlogic approved these changes
looks good to me but you may want someone else whos more familiar with the codebase to also review!

2024-02-15 14:34 UTC, pmarsh-scottlogic commented
Thanks @AAloshine-scottlogic I'll leave the PR up until end of Monday, say, so folk can weigh in if they want to

2024-02-16 12:29 UTC, chriswilty requested changes
Worthwhile cleanup 👍

Just a handful of things spotted.

2024-02-16 12:29 UTC, chriswilty commented on backend/src/openai.ts
> +		gptReply = await chatGptChatCompletion(updatedChatHistory, chatModel);
This is inside a do..while loop, so every time it is invoked, we will be creating a new OpenAI instance inside the chatGptChatCompletion function.

2024-02-16 12:29 UTC, chriswilty commented on frontend/src/components/HandbookOverlay/Pages/HandbookAttacks.test.tsx
> +} from '@src/components/HandbookOverlay/Pages/Attacks';
This is now in same directory, so can just use `from './Attacks'`

2024-02-16 12:29 UTC, chriswilty commented on frontend/src/components/HandbookOverlay/Pages/HandbookAttacks.tsx
> +} from '@src/components/HandbookOverlay/Pages/Attacks';
Same here: `from './Attacks'`

2024-02-16 12:29 UTC, chriswilty commented on frontend/src/components/HandbookOverlay/Pages/HandbookGlossary.test.tsx
> +import { GLOSSARY } from '@src/components/HandbookOverlay/Pages/Glossary';
Same idea here - this file is now in same directory.

2024-02-16 12:29 UTC, chriswilty commented on frontend/src/components/HandbookOverlay/Pages/HandbookGlossary.tsx
> +import { GLOSSARY } from '@src/components/HandbookOverlay/Pages/Glossary';
And same here - this file is now in same directory.

2024-02-19 11:11 UTC, pmarsh-scottlogic commented on backend/src/openai.ts
> +function getChatCompletionsInLimitedContextWindow(
I'ts a description I got from the console.log in the same function.

A quick Google reveals that it is a recognised term [[article](https://www.hopsworks.ai/dictionary/context-window-for-llms), [article](https://blog.google/technology/ai/long-context-window-ai-models/)].

It is also a tem userd by OpenAI, e.g. https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

2024-02-19 11:13 UTC, pmarsh-scottlogic commented on backend/src/openai.ts
>  	const completions = chatHistory.reduce<ChatCompletionMessageParam[]>(
yeah good spot, I'll change that

2024-02-19 11:31 UTC, pmarsh-scottlogic commented on backend/src/openai.ts
>  	const completions = chatHistory.reduce<ChatCompletionMessageParam[]>(
We need to get all the completions, but not every chatMessage has a completion. So i've swapped it for a map then a filter:

```typescript
const completions = chatHistory
	.map((chatMessage) =>
		'completion' in chatMessage ? chatMessage.completion : null
	)
	.filter(
		(completion) => completion !== null
	) as ChatCompletionMessageParam[];
```

I'm sure there's a nicer way though. I'm sure you've helped me with this particular scenario before as well, but I can't find where

2024-02-21 09:51 UTC, chriswilty commented on backend/src/openai.ts
>  	const completions = chatHistory.reduce<ChatCompletionMessageParam[]>(
Oh, this rings a bell now... It was the awkward typings that meant the reduce seemed like the least verbose solution. I seem to recall you couldn't simply filter then map, as then you needed the type check in both places. Oh well.

2024-02-21 09:55 UTC, chriswilty commented on backend/src/utils/token.ts
> +// The size of each model's context window in muber of tokens. https://platform.openai.com/docs/models
muber 🤪

2024-02-21 09:55 UTC, chriswilty approved these changes
All good 👌

2024-02-21 10:33 UTC, merged