Level 1 mission info conversation & modal zoom
ScottLogic/prompt-injection pull request #882
Opened 2024-03-27 15:25 UTC by dhinrichs-scottlogic

## Description
Updated the Level1 mission info conversation text. 
Changed the responsiveness of the multipage overlays so that the header is less squished at 150% zoom.

## Screenshots
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/98b73c8a-8403-4eed-8b1a-dcd9e469ff70)

## Checklist

Have you done the following?

- [ ] Linked the relevant Issue
- [ ] Added tests
- [ ] Ensured the workflow steps are passing

2024-03-27 16:43 UTC, chriswilty commented
Hmm. Do the "columnar" buttons save us any vertical space?

2024-03-27 16:54 UTC, dhinrichs-scottlogic commented
> Hmm. Do the "columnar" buttons save us any vertical space?

They do indeed. 
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/93ef6b9c-f061-482a-bbf3-20a0acc9b582)

2024-03-28 08:48 UTC, chriswilty commented
> > Hmm. Do the "columnar" buttons save us any vertical space?
> > @chriswilty
> > They do indeed.
> > ![image](https://private-user-images.githubusercontent.com/125262707/317362983-93ef6b9c-f061-482a-bbf3-20a0acc9b582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTU3NjQsIm5iZiI6MTcxMTYxNTQ2NCwicGF0aCI6Ii8xMjUyNjI3MDcvMzE3MzYyOTgzLTkzZWY2YjljLWYwNjEtNDgyYS1iYmYzLTIwYTBhY2M5YjU4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwODQ0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmM4ZDRlMWNlZWQ3ZjViMGM4NmY0ZGUwMTExOGUxYmI2YjU0NzgxMzZmNDY5ZTE1MjE0OGRkZDc5ZjdjOTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WOhhJjRrEcop3Ogv8j9DHoW1r4ODwWo0OVITGk-q4Ao)

Here's another suggestion, don't immediately dismiss it 😅
Do we really need to see the full mission info after completing level 3? How about if we simply replaced the full mission info with the Congrats button? Why would a user need to see the full level 3 mission info after beating the level? If they want to try the level again they can reset it, or if they move to a different level then back again, they'll see the dialog. I think we're making life difficult for ourselves, and those stacked buttons look pretty ugly...

2024-03-28 10:44 UTC, chriswilty requested changes
Looking good, yes I think on reflection we're ok to use the stacked buttons, but I suggest adjusting the gaps a little.

2024-03-28 10:44 UTC, chriswilty commented on frontend/src/components/LevelMissionInfoBanner/LevelMissionInfoBanner.css
> +	padding: 0 1.5rem;
I think we leave this at 0.5rem top and bottom. On the smallest breakpoint I also knocked down the gap on this class from 1.5 to 1.25rem. Could possibly go down to 1rem, unsure.

2024-03-28 10:44 UTC, chriswilty commented on frontend/src/components/LevelMissionInfoBanner/LevelMissionInfoBanner.css
> +		gap: 0.125rem;
I think this can stay at 0.5rem, seems little to gain from squishing the buttons together.

2024-03-28 14:36 UTC, chriswilty approved these changes
Lovely 👌

2024-03-28 14:49 UTC, merged